apiVersion: v1
kind: Secret
metadata:
  name: eightbitsaxlounge-ui-secrets
  namespace: eightbitsaxlounge
  labels:
    app: eightbitsaxlounge
    component: ui
type: Opaque
stringData:
  client-id: "placeholder"
  client-secret: "placeholder"
  token: "placeholder"
  midi-client-id: "placeholder"
  midi-client-secret: "placeholder"