apiVersion: apps/v1
kind: Deployment
metadata:
  name: eightbitsaxlounge-db
  labels:
    app: eightbitsaxlounge
    component: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: eightbitsaxlounge
      component: db
  template:
    metadata:
      labels:
        app: eightbitsaxlounge
        component: db
        version: "{{ lookup('env', 'VERSION') | default('latest', true) }}"
    spec:
      containers:
      - name: couchdb
        image: ghcr.io/mchellmer/eightbitsaxlounge-db:latest
        ports:
        - containerPort: 5984
          name: http
        startupProbe:
          httpGet:
            path: /_up
            port: 5984
          periodSeconds: 2
          failureThreshold: 60
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /_up
            port: 5984
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /_up
            port: 5984
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        env:
        - name: COUCHDB_USER
          value: admin
        - name: COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-db-couchdb
              key: password
        - name: NODENAME
          value: "couchdb@127.0.0.1"
        volumeMounts:
        - name: couchdb-data
          mountPath: /opt/couchdb/data
      volumes:
      - name: couchdb-data
        persistentVolumeClaim:
          claimName: couchdb-data