apiVersion: v1
kind: Service
metadata:
  name: eightbitsaxlounge-overlay
  labels:
    app: eightbitsaxlounge
    component: overlay
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: eightbitsaxlounge
    component: overlay
