apiVersion: v1
kind: ConfigMap
metadata:
  name: eightbitsaxlounge-midi-config
  namespace: eightbitsaxlounge
  labels:
    app: eightbitsaxlounge
    component: midi
data:
  device_service_url: "placeholder"
  token_expiry_minutes: "60"
