apiVersion: v1
kind: Secret
metadata:
  name: eightbitsaxlounge-midi-secrets
  namespace: eightbitsaxlounge
  labels:
    app: eightbitsaxlounge
    component: midi
type: Opaque
stringData:
  secret-key: "placeholder"
  issuer: "placeholder"
  audience: "placeholder"
  client-0-id: "placeholder"
  client-0-secret: "placeholder"
  client-1-id: "placeholder"
  client-1-secret: "placeholder"
  connection-string: "placeholder"
