apiVersion: v1
kind: Service
metadata:
  name: eightbitsaxlounge-midi-service
  labels:
    app: eightbitsaxlounge
    component: midi
spec:
  type: ClusterIP
  selector:
    app: eightbitsaxlounge
    component: midi
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
