name: Data Release

on:
  workflow_dispatch:
  push:
    branches:
      - datainit
      - main
    paths:
      - 'data/version.txt'

jobs:
  build-and-push:
    name: Build and Push Data Image
    runs-on: self-hosted
    permissions:
      packages: write
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      working-directory: ./data
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/eightbitsaxlounge-couchdb-api:latest .
        docker push ghcr.io/${{ github.repository_owner }}/eightbitsaxlounge-couchdb-api:latest

  deploy:
    name: Deploy Data API to Kubernetes
    needs: build-and-push
    runs-on: self-hosted
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Namespace Based on Branch
      id: set-namespace
      run: |
        if [[ "${{ github.ref_name }}" == "main" ]]; then
          echo "namespace=eightbitsaxlounge-prod" >> $GITHUB_ENV
        else
          echo "namespace=eightbitsaxlounge-dev" >> $GITHUB_ENV
        fi

    - name: Deploy CouchDB via Ansible
      working-directory: ./data
      env:
        NAMESPACE: ${{ env.namespace }}
      run: make deploy-data-api
