name: Data Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - data/*
    paths:
      - 'data/version.txt'

jobs:
  release:
    name: Release Data Component
    permissions:
      packages: write
      security-events: write
    uses: ./.github/workflows/release-template.yaml
    with:
      component: 'data'
      lint-target: 'lint'
      test-target: 'test'
      build-target: 'build'
      deploy-target: 'deploy'
      requires-docker-login: true
