name: MIDI Data Init

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  init-datamodel:
    name: Initialize MIDI Datamodel
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./midi
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Namespace Based on Environment
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "prod" ]]; then
            echo "NAMESPACE=eightbitsaxlounge-prod" >> $GITHUB_ENV
          else
            echo "NAMESPACE=eightbitsaxlounge-dev" >> $GITHUB_ENV
          fi

      - name: Run Data Init
        run: make data-init
        env:
          NAMESPACE: ${{ env.NAMESPACE }}
          AUTH_CLIENT_0_ID: ${{ secrets.AUTHENTICATION_CLIENTS_0_CLIENTID }}
          AUTH_CLIENT_0_SECRET: ${{ secrets.AUTHENTICATION_CLIENTS_0_CLIENTSECRET }}
