name: Monitoring Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - monitoring/*
    paths:
      - 'monitoring/version.txt'

jobs:
  release:
    name: Release Monitoring Component
    permissions:
      packages: write
      security-events: write
    uses: ./.github/workflows/release-template.yaml
    with:
      component: 'monitoring'
      deploy-target: 'deploy'
      requires-docker-login: false
