name: Security Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - security/*
    paths:
      - 'security/version.txt'

jobs:
  release:
    name: Release Security Component
    permissions:
      packages: write
      security-events: write
    uses: ./.github/workflows/release-template.yaml
    with:
      component: 'security'
      test-target: 'test'
      build-target: 'build-image'
      deploy-target: 'deploy'
      requires-docker-login: true
    secrets:
      component-secrets: |
        {
          "GITHUB_PAT": "${{ secrets.SECURITY_GITHUB_PAT }}"
        }